/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nToken_nToken */

#ifndef _Included_nToken_nToken
#define _Included_nToken_nToken
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nToken_nToken
 * Method:    callNToken
 * Signature: ([B[B)[C
 */
JNIEXPORT jcharArray JNICALL Java_nToken_nToken_callNToken
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
