/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include <vector>
#include <cstdint>
#include <iostream>
#include <locale>
#include <codecvt>
#include <string>
/* Header for class nToken */

#ifndef linkWithJAVA
#define linkWithJAVA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nToken
 * Method:    callNToken
 * Signature: ([B[B)[C
 */
JNIEXPORT jcharArray JNICALL Java_nToken_callNToken
        (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
